### ISSUE TITLE
Why nix-serve instead of nix-copy-closure?

### ISSUE THREAD

**Issue by roberth** [misuzu/nix-simple-deploy#3]
I am wondering, because nix-copy-closure is a simpler solution, not having to deal with signing.

**Comment by misuzu** [comment]
Because I want to deal with signing. You can still use [nix-deploy](https://github.com/awakesecurity/nix-deploy) (signing is broken there) which uses `nix-copy-closure`.

**Comment by roberth** [comment]
Fair enough. My workflow doesn't involve signing by the deployment tool, so this project is probably just not for me then.
"I want to" isn't very convincing, but of course that's not necessary :)

**Comment by misuzu** [comment]
Neither `nix copy` nor `nix-copy-closure` allows signing nix store path on the fly.
@roberth please check if https://github.com/misuzu/nix-simple-deploy/commit/d2d0e5d56393598a2136277644720ee61e8d86fc works for you, `signing-key` should be optional now.
